// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace MovieTraders.Data
{
    public partial class StaticData
    {
        public static List<Genre> GenreList = new List<Genre>()
        {
            new Genre((byte)1, @"Action"),
            new Genre((byte)2, @"Adventure"),
            new Genre((byte)3, @"Animation"),
            new Genre((byte)4, @"Biography"),
            new Genre((byte)5, @"Comedy"),
            new Genre((byte)6, @"Crime"),
            new Genre((byte)7, @"Documentary"),
            new Genre((byte)8, @"Drama"),
            new Genre((byte)9, @"Family"),
            new Genre((byte)10, @"Fantasy"),
            new Genre((byte)11, @"Film Noir"),
            new Genre((byte)12, @"History"),
            new Genre((byte)13, @"Horror"),
            new Genre((byte)14, @"Music"),
            new Genre((byte)15, @"Musical"),
            new Genre((byte)16, @"Mystery"),
            new Genre((byte)17, @"Romance"),
            new Genre((byte)18, @"Sci-Fi"),
            new Genre((byte)19, @"Short Film"),
            new Genre((byte)20, @"Sport"),
            new Genre((byte)21, @"Superhero"),
            new Genre((byte)22, @"Thriller"),
            new Genre((byte)23, @"War"),
            new Genre((byte)24, @"Western"),
        };
    }

    public class Genre
    {
        public Genre(byte GenreId, string Name)
        {
            this.GenreId = GenreId;
            this.Name = Name;
        }

        public byte GenreId  { get; }
        public string Name  { get; }
    }
}
