// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;

namespace MovieTraders.Data
{
    public partial class StaticData
    {
        public static List<TradeStatus> TradeStatusList = new List<TradeStatus>()
        {
            new TradeStatus((byte)1, @"Initiated", @"Requesting user created a trade"),
            new TradeStatus((byte)2, @"Notification Sent", @"Notification sent to response user"),
            new TradeStatus((byte)3, @"Accepted", @"Response user selected movies and accepted trade"),
            new TradeStatus((byte)4, @"Rejected", @"Response user rejected trade"),
            new TradeStatus((byte)5, @"Completed", @"The trade was completed and movies exchanged"),
            new TradeStatus((byte)6, @"Reversed", @"The movies have been returned to each party"),
        };
    }

    public class TradeStatus
    {
        public TradeStatus(byte TradeStatusId, string Name, string Description)
        {
            this.TradeStatusId = TradeStatusId;
            this.Name = Name;
            this.Description = Description;
        }

        public byte TradeStatusId  { get; }
        public string Name  { get; }
        public string Description  { get; }
    }
}
