// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;
using MovieTraders.Data.Crud.Models;
namespace MovieTraders.Data.Crud
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for MovieQuery method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">MovieQueryInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetMovieQueryCommand(SqlConnection cnn, IMovieQueryInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[crud].[MovieQuery]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Title",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 64,
				Value = input.Title
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        /// <summary>
        /// Reads out variables and return values from the command
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void SetMovieQueryCommandOutputs(SqlCommand cmd, MovieQueryOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (MovieQueryOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        /// <summary>
        /// Reads values from the populated reader and assigns values to properties of returned object
        /// </summary>
        /// <param name="rdr">Active SqlDataReader instance</param>
        /// <returns>Instance of MovieQueryResult</returns>
        private MovieQueryResult GetMovieQueryResultFromReader(SqlDataReader rdr)
        {
            MovieQueryResult result = new MovieQueryResult();

            result.MovieId = rdr.GetInt32(0);

            result.GenreId = rdr.GetByte(1);

            result.Year = rdr.GetInt32(2);

            result.Title = rdr.GetString(3);

            result.Link = rdr.GetString(4);

            result.CreatedByUserId = rdr.GetInt32(5);

            result.CreatedDate = rdr.GetDateTime(6);

            return result;
        }


        /// <summary>
        /// Executes the command and processes the results
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void MovieQueryCommand(SqlCommand cmd, MovieQueryOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<MovieQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetMovieQueryResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetMovieQueryCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Executes the command and processes the results async
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private async Task MovieQueryCommandAsync(SqlCommand cmd, MovieQueryOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                output.ResultData = new List<MovieQueryResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetMovieQueryResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetMovieQueryCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Queries dbo.Movie table.
        /// SQL+ Routine: crud.MovieQuery - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class MovieQueryInput or alternatively an instance of a class implementing the IMovieQueryInput interface</param>
        /// <returns>Instance of MovieQueryOutput</returns>
        public MovieQueryOutput MovieQuery(IMovieQueryInput input)
        {
            ValidateInput(input, "MovieQuery");
            MovieQueryOutput output = new MovieQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetMovieQueryCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    MovieQueryCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetMovieQueryCommand(cnn, input))
                    {
                        cnn.Open();
						MovieQueryCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
        /// <summary>
        /// Queries dbo.Movie table.
        /// SQL+ Routine: crud.MovieQuery - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class MovieQueryInput or alternatively an instance of a class implementing the IMovieQueryInput interface</param>
        /// <returns>Instance of MovieQueryOutput</returns>
        public async Task<MovieQueryOutput> MovieQueryAsync(IMovieQueryInput input)
        {
            ValidateInput(input, "MovieQueryAsync");
            MovieQueryOutput output = new MovieQueryOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetMovieQueryCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    await MovieQueryCommandAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetMovieQueryCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await MovieQueryCommandAsync(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
    }
}