// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Interface for UserInsertInput object.
    /// </summary>
    public interface IUserInsertInput : IValidInput
    {
        short? CountyId { set; get; }
        int? PasswordIterations { set; get; }
        byte[] PasswordHash { set; get; }
        byte[] PasswordSalt { set; get; }
        string Phone { set; get; }
        string Email { set; get; }
        string Name { set; get; }
        DateTime? LockDate { set; get; }
        string LockReason { set; get; }
    }

    /// <summary>
    /// Input object for UserInsert method.
    /// </summary>
    public class UserInsertInput : ValidInput, IUserInsertInput
    {
        /// <summary>
        /// CountyId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public short? CountyId { set; get; }

        /// <summary>
        /// PasswordIterations
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? PasswordIterations { set; get; }

        /// <summary>
        /// PasswordHash
        /// </summary>
        [MaxLength(16)]
        [Required(AllowEmptyStrings = false)]
        public byte[] PasswordHash { set; get; }

        /// <summary>
        /// PasswordSalt
        /// </summary>
        [MaxLength(16)]
        [Required(AllowEmptyStrings = false)]
        public byte[] PasswordSalt { set; get; }

        /// <summary>
        /// Phone
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [StringLength(16, MinimumLength = 0)]
        public string Phone { set; get; }

        /// <summary>
        /// Email
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [StringLength(64, MinimumLength = 0)]
        public string Email { set; get; }

        /// <summary>
        /// Name
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [StringLength(64, MinimumLength = 0)]
        public string Name { set; get; }

        /// <summary>
        /// LockDate
        /// </summary>
        public DateTime? LockDate { set; get; }

        /// <summary>
        /// LockReason
        /// </summary>
        [StringLength(256, MinimumLength = 0)]
        public string LockReason { set; get; }

    }
} 