// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Interface for UserForForgotPasswordInput object.
    /// </summary>
    public interface IUserForForgotPasswordInput : IValidInput
    {
        string Email { set; get; }
        string Phone { set; get; }
    }

    /// <summary>
    /// Input object for UserForForgotPassword method.
    /// </summary>
    public class UserForForgotPasswordInput : ValidInput, IUserForForgotPasswordInput
    {
        /// <summary>
        /// Email
        /// </summary>
        [EmailAddress]
        [Required(AllowEmptyStrings = false)]
        public string Email { set; get; }

        /// <summary>
        /// Phone
        /// </summary>
        [Phone]
        [Required(AllowEmptyStrings = false)]
        public string Phone { set; get; }

    }
} 