// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Interface for UserSetPasswordInput object.
    /// </summary>
    public interface IUserSetPasswordInput : IValidInput
    {
        int? UserId { set; get; }
        int? PasswordIterations { set; get; }
        byte[] PasswordSalt { set; get; }
        byte[] PasswordHash { set; get; }
    }

    /// <summary>
    /// Input object for UserSetPassword method.
    /// </summary>
    public class UserSetPasswordInput : ValidInput, IUserSetPasswordInput
    {
        [Required(AllowEmptyStrings = false)]
        public int? UserId { set; get; }

        [Required(AllowEmptyStrings = false)]
        public int? PasswordIterations { set; get; }

        [MaxLength(16)]
        [Required(AllowEmptyStrings = false)]
        public byte[] PasswordSalt { set; get; }

        [MaxLength(16)]
        [Required(AllowEmptyStrings = false)]
        public byte[] PasswordHash { set; get; }

    }
} 