// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Interface for UserLockInput object.
    /// </summary>
    public interface IUserLockInput : IValidInput
    {
        int? UserId { set; get; }
        string LockReason { set; get; }
    }

    /// <summary>
    /// Input object for UserLock method.
    /// </summary>
    public class UserLockInput : ValidInput, IUserLockInput
    {
        [Required(AllowEmptyStrings = false)]
        public int? UserId { set; get; }

        [Display(Name = "Lock Reason", Description = "Lock Reason")]
        [MaxLength(256)]
        [Required(AllowEmptyStrings = false)]
        public string LockReason { set; get; }

    }
} 