// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Output object for UserInsert method.
    /// </summary>
    public partial class UserInsertOutput
    {
        public enum Returns
        {
             Ok = 1,
             Conflict = 2
        }
		/// <summary>
		/// UserId
		/// </summary>
		public int? UserId { set; get; }
		public Returns ReturnValue { set; get; }
    }
}