// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Interface for UserLockInfoInput object.
    /// </summary>
    public interface IUserLockInfoInput : IValidInput
    {
        int? UserId { set; get; }
    }

    /// <summary>
    /// Input object for UserLockInfo method.
    /// </summary>
    public class UserLockInfoInput : ValidInput, IUserLockInfoInput
    {
        /// <summary>
        /// UserId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? UserId { set; get; }

    }
} 