// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace MovieTraders.Data.Extended.Models
{
    /// <summary>
    /// Result object for UserLockInfo routine.
    /// </summary>
    public partial class UserLockInfoResult
	{
        public DateTime? LockDate { set; get; }
        public string LockReason { set; get; }
    }
}