// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace MovieTraders.Data.Enumerations
{
    public enum TradeStatuses : System.Byte
    {
        Initiated = 1,
        Notified = 2,
        Accepted = 3,
        Rejected = 4,
        Completed = 5,
        Reversed = 6
    }
}
