// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Interface for MoviesByCountyInput object.
    /// </summary>
    public interface IMoviesByCountyInput : IValidInput
    {
        int? UserId { set; get; }
        int? PageSize { set; get; }
        int? PageNumber { set; get; }
    }

    /// <summary>
    /// Input object for MoviesByCounty method.
    /// </summary>
    public class MoviesByCountyInput : ValidInput, IMoviesByCountyInput
    {
        [Required(AllowEmptyStrings = false)]
        public int? UserId { set; get; }

        [Range(typeof(int), "10", "50")]
        [Required(AllowEmptyStrings = false)]
        public int? PageSize { set; get; }

        [Range(typeof(int), "1", "2147483647")]
        [Required(AllowEmptyStrings = false)]
        public int? PageNumber { set; get; }

    }
} 