// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Output object for MoviesByCounty method.
    /// </summary>
    public partial class MoviesByCountyOutput
    {
        public enum Returns
        {
             NotFound = 0,
             Ok = 1
        }
		public int? PageCount { set; get; }
		public Returns ReturnValue { set; get; }
        /// <summary>
        /// List of MoviesByCountyResult results.
        /// </summary>
        public List<MoviesByCountyResult> ResultData { set; get; }
    }
}