// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Interface for MovieInsertInput object.
    /// </summary>
    public interface IMovieInsertInput : IValidInput
    {
        byte? GenreId { set; get; }
        int? Year { set; get; }
        string Title { set; get; }
        string Link { set; get; }
        int? CreatedByUserId { set; get; }
    }

    /// <summary>
    /// Input object for MovieInsert method.
    /// </summary>
    public class MovieInsertInput : ValidInput, IMovieInsertInput
    {
        /// <summary>
        /// GenreId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public byte? GenreId { set; get; }

        /// <summary>
        /// Year
        /// </summary>
        [Range(typeof(int), "1900", "2050")]
        [Required(AllowEmptyStrings = false)]
        public int? Year { set; get; }

        /// <summary>
        /// Title
        /// </summary>
        [MaxLength(64)]
        [Required(AllowEmptyStrings = false)]
        [StringLength(64, MinimumLength = 1)]
        public string Title { set; get; }

        /// <summary>
        /// Link
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [StringLength(1024, MinimumLength = 1)]
        [Url]
        public string Link { set; get; }

        /// <summary>
        /// CreatedByUserId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? CreatedByUserId { set; get; }

    }
} 