// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Result object for MovieQuery routine.
    /// </summary>
    public partial class MovieQueryResult
	{
        public int MovieId { set; get; }
        public byte GenreId { set; get; }
        public int Year { set; get; }
        public string Title { set; get; }
        public string Link { set; get; }
        public int CreatedByUserId { set; get; }
        public DateTime CreatedDate { set; get; }
    }
}