// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Interface for MovieQueryInput object.
    /// </summary>
    public interface IMovieQueryInput : IValidInput
    {
        string Title { set; get; }
    }

    /// <summary>
    /// Input object for MovieQuery method.
    /// </summary>
    public class MovieQueryInput : ValidInput, IMovieQueryInput
    {
        /// <summary>
        /// Title
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        [StringLength(64, MinimumLength = 1)]
        public string Title { set; get; }

    }
} 