// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Result objects for UserTrades routine.
    /// </summary>
    public partial class UserTradesResult
	{
            public List<Trades> TradesResult { set; get; }
            public class Trades
            {
                public int TradeId { set; get; }
                public byte TradeStatusId { set; get; }
                public int RequestUserId { set; get; }
                public string RequestUserName { set; get; }
                public int ResponseUserId { set; get; }
                public string ResponseUserName { set; get; }
                public DateTime RequestDate { set; get; }
                public int RequestDuration { set; get; }
                public string Notes { set; get; }
            }
            public List<Movies> MoviesResult { set; get; }
            public class Movies
            {
                public int TradeId { set; get; }
                public int RequestUserId { set; get; }
                public string RequestMovieTitle { set; get; }
                public int RequestMovieYear { set; get; }
                public byte RequestMovieFormat { set; get; }
                public int ResponseUserId { set; get; }
                public string ResponseMovieTitle { set; get; }
                public int ResponseMovieYear { set; get; }
                public byte ResponseMovieFormat { set; get; }
            }
    }
}