// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Interface for UserMovieQueryInput object.
    /// </summary>
    public interface IUserMovieQueryInput : IValidInput
    {
        int? UserId { set; get; }
        int? MovieId { set; get; }
    }

    /// <summary>
    /// Input object for UserMovieQuery method.
    /// </summary>
    public class UserMovieQueryInput : ValidInput, IUserMovieQueryInput
    {
        [Required(AllowEmptyStrings = false)]
        public int? UserId { set; get; }

        public int? MovieId { set; get; }

    }
} 