// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MovieTraders.Data.UserDefinedTypes;

namespace MovieTraders.Data.Crud.Models
{
    /// <summary>
    /// Interface for UserMovieMergeInput object.
    /// </summary>
    public interface IUserMovieMergeInput : IValidInput
    {
        int? UserId { set; get; }
        int? MovieId { set; get; }
        List<ITinyInts> Formats { set; get; }
    }

    /// <summary>
    /// Input object for UserMovieMerge method.
    /// </summary>
    public class UserMovieMergeInput : ValidInput, IUserMovieMergeInput
    {
        /// <summary>
        /// UserId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? UserId { set; get; }

        /// <summary>
        /// MovieId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? MovieId { set; get; }

        [Required(AllowEmptyStrings = false)]
        public List<ITinyInts> Formats { set; get; }

    }
} 