// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;
using MovieTraders.Data.Extended.Models;
namespace MovieTraders.Data.Extended
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for UserLock method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">UserLockInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetUserLockCommand(SqlConnection cnn, IUserLockInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[ext].[UserLock]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UserId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.UserId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LockReason",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 256,
				Value = input.LockReason
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        /// <summary>
        /// Reads out variables and return values from the command
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void SetUserLockCommandOutputs(SqlCommand cmd, UserLockOutput output)
        {
            if(cmd.Parameters[2].Value != DBNull.Value)
            {
                output.ReturnValue = (UserLockOutput.Returns)cmd.Parameters[2].Value;
            }
        }
        /// <summary>
        /// Executes the command and processes the results
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void UserLockCommand(SqlCommand cmd, UserLockOutput output)
        {
            cmd.ExecuteNonQuery();
            SetUserLockCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Executes the command and processes the results async
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private async Task UserLockCommandAsync(SqlCommand cmd, UserLockOutput output)
        {
            await cmd.ExecuteNonQueryAsync();
            SetUserLockCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Sets lock date and lock reason for given UserId - lock date is automatically assigned.
        /// SQL+ Routine: ext.UserLock - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserLockInput or alternatively an instance of a class implementing the IUserLockInput interface</param>
        /// <returns>Instance of UserLockOutput</returns>
        public UserLockOutput UserLock(IUserLockInput input)
        {
            ValidateInput(input, "UserLock");
            UserLockOutput output = new UserLockOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserLockCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    UserLockCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserLockCommand(cnn, input))
                    {
                        cnn.Open();
						UserLockCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
        /// <summary>
        /// Sets lock date and lock reason for given UserId - lock date is automatically assigned.
        /// SQL+ Routine: ext.UserLock - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserLockInput or alternatively an instance of a class implementing the IUserLockInput interface</param>
        /// <returns>Instance of UserLockOutput</returns>
        public async Task<UserLockOutput> UserLockAsync(IUserLockInput input)
        {
            ValidateInput(input, "UserLockAsync");
            UserLockOutput output = new UserLockOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserLockCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    await UserLockCommandAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserLockCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await UserLockCommandAsync(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
    }
}