// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;
using MovieTraders.Data.Extended.Models;
namespace MovieTraders.Data.Extended
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for UserLockInfo method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">UserLockInfoInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetUserLockInfoCommand(SqlConnection cnn, IUserLockInfoInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[ext].[UserLockInfo]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UserId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.UserId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        /// <summary>
        /// Reads out variables and return values from the command
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void SetUserLockInfoCommandOutputs(SqlCommand cmd, UserLockInfoOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (UserLockInfoOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        /// <summary>
        /// Reads values from the populated reader and assigns values to properties of returned object
        /// </summary>
        /// <param name="rdr">Active SqlDataReader instance</param>
        /// <returns>Instance of UserLockInfoResult</returns>
        private UserLockInfoResult GetUserLockInfoResultFromReader(SqlDataReader rdr)
        {
            UserLockInfoResult result = new UserLockInfoResult();

            if(!rdr.IsDBNull(0))
            {
                result.LockDate = rdr.GetDateTime(0);
            }

            if(!rdr.IsDBNull(1))
            {
                result.LockReason = rdr.GetString(1);
            }

            return result;
        }


        /// <summary>
        /// Executes the command and processes the results
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void UserLockInfoCommand(SqlCommand cmd, UserLockInfoOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = GetUserLockInfoResultFromReader(rdr);
                }
                rdr.Close();
            }
            SetUserLockInfoCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Executes the command and processes the results async
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private async Task UserLockInfoCommandAsync(SqlCommand cmd, UserLockInfoOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if(rdr.Read())
                {
                    output.ResultData = GetUserLockInfoResultFromReader(rdr);
                }
                rdr.Close();
            }
            SetUserLockInfoCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Retrieves lock information for the user based on user id.
        /// SQL+ Routine: ext.UserLockInfo - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserLockInfoInput or alternatively an instance of a class implementing the IUserLockInfoInput interface</param>
        /// <returns>Instance of UserLockInfoOutput</returns>
        public UserLockInfoOutput UserLockInfo(IUserLockInfoInput input)
        {
            ValidateInput(input, "UserLockInfo");
            UserLockInfoOutput output = new UserLockInfoOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserLockInfoCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    UserLockInfoCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserLockInfoCommand(cnn, input))
                    {
                        cnn.Open();
						UserLockInfoCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
        /// <summary>
        /// Retrieves lock information for the user based on user id.
        /// SQL+ Routine: ext.UserLockInfo - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserLockInfoInput or alternatively an instance of a class implementing the IUserLockInfoInput interface</param>
        /// <returns>Instance of UserLockInfoOutput</returns>
        public async Task<UserLockInfoOutput> UserLockInfoAsync(IUserLockInfoInput input)
        {
            ValidateInput(input, "UserLockInfoAsync");
            UserLockInfoOutput output = new UserLockInfoOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserLockInfoCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    await UserLockInfoCommandAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserLockInfoCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await UserLockInfoCommandAsync(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
    }
}