// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;
using MovieTraders.Data.Extended.Models;
namespace MovieTraders.Data.Extended
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for UserForForgotPassword method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">UserForForgotPasswordInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetUserForForgotPasswordCommand(SqlConnection cnn, IUserForForgotPasswordInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[ext].[UserForForgotPassword]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Email",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 64,
				Value = input.Email
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Phone",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 16,
				Value = input.Phone
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        /// <summary>
        /// Reads out variables and return values from the command
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void SetUserForForgotPasswordCommandOutputs(SqlCommand cmd, UserForForgotPasswordOutput output)
        {
            if(cmd.Parameters[2].Value != DBNull.Value)
            {
                output.ReturnValue = (UserForForgotPasswordOutput.Returns)cmd.Parameters[2].Value;
            }
        }

        /// <summary>
        /// Reads values from the populated reader and assigns values to properties of returned object
        /// </summary>
        /// <param name="rdr">Active SqlDataReader instance</param>
        /// <returns>Instance of UserForForgotPasswordResult</returns>
        private UserForForgotPasswordResult GetUserForForgotPasswordResultFromReader(SqlDataReader rdr)
        {
            UserForForgotPasswordResult result = new UserForForgotPasswordResult();

            result.UserId = rdr.GetInt32(0);

            result.Name = rdr.GetString(1);

            if(!rdr.IsDBNull(2))
            {
                result.LockDate = rdr.GetDateTime(2);
            }

            if(!rdr.IsDBNull(3))
            {
                result.LockReason = rdr.GetString(3);
            }

            return result;
        }


        /// <summary>
        /// Executes the command and processes the results
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void UserForForgotPasswordCommand(SqlCommand cmd, UserForForgotPasswordOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                if(rdr.Read())
                {
                    output.ResultData = GetUserForForgotPasswordResultFromReader(rdr);
                }
                rdr.Close();
            }
            SetUserForForgotPasswordCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Executes the command and processes the results async
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private async Task UserForForgotPasswordCommandAsync(SqlCommand cmd, UserForForgotPasswordOutput output)
        {
            using (SqlDataReader rdr = await cmd.ExecuteReaderAsync())
            {
                if(rdr.Read())
                {
                    output.ResultData = GetUserForForgotPasswordResultFromReader(rdr);
                }
                rdr.Close();
            }
            SetUserForForgotPasswordCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Retrieves password details and lock information for the user for users email.
        /// SQL+ Routine: ext.UserForForgotPassword - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserForForgotPasswordInput or alternatively an instance of a class implementing the IUserForForgotPasswordInput interface</param>
        /// <returns>Instance of UserForForgotPasswordOutput</returns>
        public UserForForgotPasswordOutput UserForForgotPassword(IUserForForgotPasswordInput input)
        {
            ValidateInput(input, "UserForForgotPassword");
            UserForForgotPasswordOutput output = new UserForForgotPasswordOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserForForgotPasswordCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    UserForForgotPasswordCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserForForgotPasswordCommand(cnn, input))
                    {
                        cnn.Open();
						UserForForgotPasswordCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
        /// <summary>
        /// Retrieves password details and lock information for the user for users email.
        /// SQL+ Routine: ext.UserForForgotPassword - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserForForgotPasswordInput or alternatively an instance of a class implementing the IUserForForgotPasswordInput interface</param>
        /// <returns>Instance of UserForForgotPasswordOutput</returns>
        public async Task<UserForForgotPasswordOutput> UserForForgotPasswordAsync(IUserForForgotPasswordInput input)
        {
            ValidateInput(input, "UserForForgotPasswordAsync");
            UserForForgotPasswordOutput output = new UserForForgotPasswordOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserForForgotPasswordCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    await UserForForgotPasswordCommandAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserForForgotPasswordCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await UserForForgotPasswordCommandAsync(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
    }
}