// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;
using MovieTraders.Data.Extended.Models;
namespace MovieTraders.Data.Extended
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for UserInsert method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">UserInsertInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetUserInsertCommand(SqlConnection cnn, IUserInsertInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[ext].[UserInsert]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UserId",
                Direction = ParameterDirection.Output,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@CountyId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.SmallInt,
                Scale = 0,
                Precision = 5,
				Value = input.CountyId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PasswordIterations",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.PasswordIterations
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PasswordHash",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Binary,
                Size = 16,
				Value = input.PasswordHash
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@PasswordSalt",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Binary,
                Size = 16,
				Value = input.PasswordSalt
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Phone",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 16,
				Value = input.Phone
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Email",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 64,
				Value = input.Email
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Name",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 64,
				Value = input.Name
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LockDate",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.DateTime,
                Precision = 3,
				Value = (object)input.LockDate ?? DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@LockReason",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 256,
				Value = (object)input.LockReason ?? DBNull.Value
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        /// <summary>
        /// Reads out variables and return values from the command
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void SetUserInsertCommandOutputs(SqlCommand cmd, UserInsertOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.UserId = (int?)cmd.Parameters[0].Value;
            }
            if(cmd.Parameters[10].Value != DBNull.Value)
            {
                output.ReturnValue = (UserInsertOutput.Returns)cmd.Parameters[10].Value;
            }
        }
        /// <summary>
        /// Executes the command and processes the results
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void UserInsertCommand(SqlCommand cmd, UserInsertOutput output)
        {
            cmd.ExecuteNonQuery();
            SetUserInsertCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Executes the command and processes the results async
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private async Task UserInsertCommandAsync(SqlCommand cmd, UserInsertOutput output)
        {
            await cmd.ExecuteNonQueryAsync();
            SetUserInsertCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Inserts a new record into the dbo.User table.
        /// SQL+ Routine: ext.UserInsert - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserInsertInput or alternatively an instance of a class implementing the IUserInsertInput interface</param>
        /// <returns>Instance of UserInsertOutput</returns>
        public UserInsertOutput UserInsert(IUserInsertInput input)
        {
            ValidateInput(input, "UserInsert");
            UserInsertOutput output = new UserInsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserInsertCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    UserInsertCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserInsertCommand(cnn, input))
                    {
                        cnn.Open();
						UserInsertCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
        /// <summary>
        /// Inserts a new record into the dbo.User table.
        /// SQL+ Routine: ext.UserInsert - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserInsertInput or alternatively an instance of a class implementing the IUserInsertInput interface</param>
        /// <returns>Instance of UserInsertOutput</returns>
        public async Task<UserInsertOutput> UserInsertAsync(IUserInsertInput input)
        {
            ValidateInput(input, "UserInsertAsync");
            UserInsertOutput output = new UserInsertOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserInsertCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    await UserInsertCommandAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserInsertCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await UserInsertCommandAsync(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
    }
}