// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Threading.Tasks;
using MovieTraders.Data.Extended.Models;
namespace MovieTraders.Data.Extended
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for UserUnlock method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">UserUnlockInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetUserUnlockCommand(SqlConnection cnn, IUserUnlockInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[ext].[UserUnlock]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@UserId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.UserId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        /// <summary>
        /// Reads out variables and return values from the command
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void SetUserUnlockCommandOutputs(SqlCommand cmd, UserUnlockOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (UserUnlockOutput.Returns)cmd.Parameters[1].Value;
            }
        }
        /// <summary>
        /// Executes the command and processes the results
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private void UserUnlockCommand(SqlCommand cmd, UserUnlockOutput output)
        {
            cmd.ExecuteNonQuery();
            SetUserUnlockCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Executes the command and processes the results async
        /// </summary>
        /// <param name="cmd">Active SqlCommand instance</param>
        /// <param name="output">EmptyStringInsertOutput instance</param>
        private async Task UserUnlockCommandAsync(SqlCommand cmd, UserUnlockOutput output)
        {
            await cmd.ExecuteNonQueryAsync();
            SetUserUnlockCommandOutputs(cmd, output);
        }
        /// <summary>
        /// Clears the lock reason and lock date for given UserId.
        /// SQL+ Routine: ext.UserUnlock - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserUnlockInput or alternatively an instance of a class implementing the IUserUnlockInput interface</param>
        /// <returns>Instance of UserUnlockOutput</returns>
        public UserUnlockOutput UserUnlock(IUserUnlockInput input)
        {
            ValidateInput(input, "UserUnlock");
            UserUnlockOutput output = new UserUnlockOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserUnlockCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    UserUnlockCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserUnlockCommand(cnn, input))
                    {
                        cnn.Open();
						UserUnlockCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
        /// <summary>
        /// Clears the lock reason and lock date for given UserId.
        /// SQL+ Routine: ext.UserUnlock - Authored by Alan Hyneman
        /// </summary>
        /// <param name="input">An instance of class UserUnlockInput or alternatively an instance of a class implementing the IUserUnlockInput interface</param>
        /// <returns>Instance of UserUnlockOutput</returns>
        public async Task<UserUnlockOutput> UserUnlockAsync(IUserUnlockInput input)
        {
            ValidateInput(input, "UserUnlockAsync");
            UserUnlockOutput output = new UserUnlockOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetUserUnlockCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    await UserUnlockCommandAsync(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if (idx > 0)
                {
                    await Task.Delay(retryOptions.RetryIntervals[idx - 1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetUserUnlockCommand(cnn, input))
                    {
                        await cnn.OpenAsync();
						await UserUnlockCommandAsync(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    AllowRetryOrThrowError(idx, sqlException);
                }
            }
            return output;
        }
    }
}